apiVersion: v1
data:
  mapAccounts: '[]'
  mapRoles: '[{"rolearn":"arn:aws:iam::814445629751:role/K8SStackStack-EksclusterMastersRoleD85283BE-TNGTYM5J6IUU","username":"arn:aws:iam::814445629751:role/K8SStackStack-EksclusterMastersRoleD85283BE-TNGTYM5J6IUU","groups":["system:masters"]},{"rolearn":"arn:aws:iam::814445629751:role/K8SStackStack-EksclusterfargateprofiledefaultPodEx-1DNSH7W8PBXJF","username":"system:node:{{SessionName}}","groups":["system:bootstrappers","system:nodes","system:node-proxier"]},{"rolearn":"arn:aws:iam::814445629751:role/K8SStackStack-EksclusterNodegroupeksnodegropNodeGr-COQBAPL3JZ91","username":"system:node:{{EC2PrivateDNSName}}","groups":["system:bootstrappers","system:nodes"]}]'
  mapUsers: '[]'
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapAccounts":"[]","mapRoles":"[{\"rolearn\":\"arn:aws:iam::814445629751:role/K8SStackStack-EksclusterMastersRoleD85283BE-TNGTYM5J6IUU\",\"username\":\"arn:aws:iam::814445629751:role/K8SStackStack-EksclusterMastersRoleD85283BE-TNGTYM5J6IUU\",\"groups\":[\"system:masters\"]},{\"rolearn\":\"arn:aws:iam::814445629751:role/K8SStackStack-EksclusterfargateprofiledefaultPodEx-1DNSH7W8PBXJF\",\"username\":\"system:node:{{SessionName}}\",\"groups\":[\"system:bootstrappers\",\"system:nodes\",\"system:node-proxier\"]},{\"rolearn\":\"arn:aws:iam::814445629751:role/K8SStackStack-EksclusterNodegroupeksnodegropNodeGr-COQBAPL3JZ91\",\"username\":\"system:node:{{EC2PrivateDNSName}}\",\"groups\":[\"system:bootstrappers\",\"system:nodes\"]}]","mapUsers":"[]"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"aws.cdk.eks/prune-c8030bfec43daa140e0f7e90cb19733d8a742b26a4":""},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2021-04-06T11:06:36Z"
  labels:
    aws.cdk.eks/prune-c8030bfec43daa140e0f7e90cb19733d8a742b26a4: ""
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data: {}
    manager: vpcLambda
    operation: Update
    time: "2021-04-06T11:06:37Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapAccounts: {}
        f:mapRoles: {}
        f:mapUsers: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:aws.cdk.eks/prune-c8030bfec43daa140e0f7e90cb19733d8a742b26a4: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-04-06T11:07:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1241"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 96e9b5db-b1c3-4c10-9f81-a774db7f27d6
